var LoopConstants = {
  LOOPS_RECEIVED: "LOOPS RECEIVED",
  LOOP_RECEIVED: "LOOP RECEIVED",
  UPDATE_LOOP: "UPDATE LOOP",
  DELETE_LOOP: "DELETE LOOP",
  COMMENT_RECEIVED: "COMMENT_RECEIVED"
};

module.exports = LoopConstants;
